remote_theme: coursweb/jk-theme
title: Embedding Formative Assessment
description: Résumé du livre de Wiliam & Leahy (2015)
lang: fr-FR
chapters:
 - title: Lectures Pédagogie
   url: https://ms-studio.github.io/lectures-pedagogie/
# - title: Link 2
#   url: https://github.com/

   # Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Manuel Schmalstieg</li>
  <li>2023</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/jk-theme">Lien Github</a></li></ul>
